### ISSUE TITLE
Number Query

### ISSUE THREAD

**Issue by Rambatino** [matt-saenz/PyCPS#2]
I'm going to debug this further, but why when I include another column do I get 40000 more rows and also less unique values in one column?

```python
print(get_asec(2023, ["HEFAMINC"]).shape)
print(get_asec(2023, ["HEFAMINC", "a_age"]).shape)
```

(88978, 1)
(146133, 2)

**Comment by matt-saenz** [comment]
Hi @Rambatino, this is due to mixing household- and person-level variables. In the first call, you request only a household-level variable (`hefaminc`), so the Census API returns a household-level dataset. In the second call, you request a person-level variable (`a_age`), so you get a person-level dataset. Since that second call also includes a household-level variable, you also get household-level data on each person. People are within households, and all people in a given household have the same value for a household-level variable. So the behavior you are seeing is valid/to be expected.

**Comment by Rambatino** [comment]
Thank you @matt-saenz that's really helpful! :)

**Comment by matt-saenz** [comment]
Sure thing! Happy to help!
